### ISSUE TITLE
Add dropout layer to neural network

### ISSUE THREAD

**Issue by kiosklabs** [kiosklabs/kaggle-digit-recognizer-competition#4]
Please add a dropout layer to our convolutional neural network.
Can you also send me some benchmarks when you run the model on the test data? 
It's taking me around 20 mins to fit on 20 epochs.

**Comment by sctcooper** [comment]
any idea on how to go about this in nolearn? I saw one of the tutorials but it seems to use a separate neural network

**Comment by kiosklabs** [comment]
take a look at how chris did it in:
http://blog.christianperone.com/2015/08/convolutional-neural-networks-and-feature-extraction-with-python/

**Comment by sctcooper** [comment]
Hey, I had some issues with the requirements for nolearn and lasagne. I'm trying to get it installed but some error messages keep coming up

**Comment by kiosklabs** [comment]
in the ipython notebook or in terminal?

**Comment by sctcooper** [comment]
notebook. I'll work on the script instead, is that alright?

**Comment by kiosklabs** [comment]
sure, no worries man
