### ISSUE TITLE
Use GPU for better performance

### ISSUE THREAD

**Issue by kiosklabs** [kiosklabs/kaggle-digit-recognizer-competition#5]
Not really required to commit to master, but it seems we're spending a lot of time with training data.
I'm currently enabling GPU use for theano. I suggest the team should do this for improved performance.

Here's the guide to do this:
http://deeplearning.net/software/theano/tutorial/using_gpu.html

**Comment by kiosklabs** [comment]
I'm still having issues with my nvidia drivers. I'll update this once I've finished installing Cuda.

**Comment by kiosklabs** [comment]
Update: It seems like Nvidia's Cuda doesn't officially support Ubuntu 16.04.
Although Cuda 8 RC claims to officially support xenial, I pretty much doubt it's stable enough for use. Another issue is the repositories, Xenial seems to be strict in implementing hash signatures for the repos, so I wasn't able to apt-get update. Hopefully, this is resolve for Cuda 8 RC. There seems to be lots of complaint in the forums as this also seem to be an issue with tensorflow. For the mean time, let's just use cpu instead.

**Comment by sctcooper** [comment]
nw, mate. I'll try to run it here. I got Ubuntu 15.04 and GTX 660 here
